version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${PYTHON_PORT}:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DYNAMODB_ENDPOINT: ${DYNAMODB_ENDPOINT_HOST_INTERNAL}