version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "${DYNAMODB_PORT}:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      DYNAMODB_ENDPOINT: ${DYNAMODB_ENDPOINT}

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - "${DYNAMODB_ADMIN_PORT}:8001"
    environment:
      DYNAMO_ENDPOINT: ${DYNAMODB_ENDPOINT}
      AWS_REGION: ${AWS_REGION}

volumes:
  dynamodb_data:
