name: Run Suite DynamoDB Local and Verify Ports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-suite:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Execute the suite-dynamodb-local.sh script
      run: |
        sh /scripts/suite-dynamodb-local.sh

    - name: Verify DynamoDB Local and Admin UI
      run: |
        curl --fail http://localhost:8000
        curl --fail http://localhost:8001
        curl --fail http://localhost:5000

    - name: Tear down Docker Compose
      run: |
        docker-compose down --volumes --remove-orphans
